version: '3.7'
services:
  api:
    build: .
    container_name: 'deepspeech_api'
    ports:
      - '0.0.0.0:8000:8000'
    restart: 'unless-stopped'
    volumes:
      - './deepspeech_model.tflite:/app/deepspeech_model.tflite:ro'
    environment:
      - SANIC_DEBUG=${SANIC_DEBUG}
      - SANIC_TESTING=${SANIC_TESTING}
      - SANIC_HOST=${SANIC_HOST}
      - SANIC_PORT=${SANIC_PORT}
      - SANIC_ENV=${SANIC_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - SANIC_WEBSOCKET_MAX_SIZE=${SANIC_WEBSOCKET_MAX_SIZE}
      - SANIC_WEBSOCKET_PING_TIMEOUT=${SANIC_WEBSOCKET_PING_TIMEOUT}
      - SANIC_RESPONSE_TIMEOUT=${SANIC_RESPONSE_TIMEOUT}
      - SANIC_REQUEST_TIMEOUT=${SANIC_REQUEST_TIMEOUT}
      - DATABASE_URI=${DATABASE_URI}
